### ISSUE TITLE
exception during shuffle

### ISSUE THREAD

**Issue by markblundeberg** [clifordsymack/Electron-Cash#112]
on latest master: 

```
Traceback (most recent call last):
  File "/home/mark/git/shuffle/plugins/shuffle/qt.py", line 316, in _got_tx
    _got_tx_check_tentative_shuffles(window, tx)  # check for workaround to bug#70
  File "/home/mark/git/shuffle/plugins/shuffle/qt.py", line 249, in _got_tx_check_tentative_shuffles
    if CoinUtils.is_coin_shuffled(window.wallet, {'prevout_hash':txid, 'prevout_n':n}, {txid: tx}):
  File "/home/mark/git/shuffle/plugins/shuffle/coin_utils.py", line 416, in is_coin_shuffled
    getattr(wallet, "_shuffled_address_cache", set()).add(coin['address'])
KeyError: 'address'
```

**Comment by emergent-reasons** [comment]
Same for me. Also seems to have resulted in an empty description in the history.

**Comment by cculianu** [comment]
Thanks guys.  I introduced this new bug -- and I fixed it in latest git head.

Sorry and thanks for reporting!
